version: '3'

services:
  app:
    image: api/flask:v1.0
    build: .
    container_name: api_flask
    environment:
      - MYSQL_DATABASE_USER= 
      - MYSQL_DATABASE_PASSWORD= 
      - MYSQL_DATABASE_HOST= 
      - MYSQL_DATABASE_PORT= 
      - MYSQL_DATABASE_SCHEMA= 
    ports:
      - 5000:5000